---
title: "Homework 5"
author: "Alison Barbee"
date: "2022-11-30"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE)
```

```{r data}
library(readr)

homicide_data <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

#Picked Los Angeles as my primary city  

```{r Los Angeles}
library(tidyverse)
library(forcats)

losAngeles <- homicide_data %>%
  mutate(city_name = str_c(homicide_data$city, homicide_data$state, sep = ", ")) %>%
  filter(city_name == "Los Angeles, CA") %>%
  mutate(Status = case_when(
    grepl("Closed by arrest", disposition) ~ "solved", 
    grepl("Closed without arrest", disposition) ~ "unsolved",
    grepl("Open/No arrest", disposition) ~ "unsolved",
        TRUE ~ "NA")) %>%
  mutate(homicide_race = fct_lump_min(victim_race, min = 100))

```

Use different colors to show the three race groups with the highest number of homicides for that city 
(you may find the fct_lump function from forcats useful for this).

```{r, race counts}
sum(losAngeles$victim_race == "Hispanic")
sum(losAngeles$victim_race == "Black")
sum(losAngeles$victim_race == "White")
sum(losAngeles$victim_race == "Other")
sum(losAngeles$victim_race == "Asian")
sum(losAngeles$victim_race == "Unknown")
```

#Mapping it out

```{r Map, tigris_use_cache = TRUE}
library(sf)
library(tigris)
library(ggplot2)
library(viridis)
library(MAP)

ca_counties <- counties(state = "CA", cb = TRUE, class = "sf")

ggplot() + 
  geom_sf(data = ca_counties, color = "lightgray")
```

```{r}
la_homicides <- losAngeles %>% 
  select(uid, reported_date, homicide_race, lat, lon, Status)

la_homicides <- st_as_sf(la_homicides, coords = c("lon", "lat")) %>%
  st_set_crs(4269)

```

```{r, final map}
ggplot() +
  geom_sf(data = ca_counties, color = "lightgray", fill = "gray") +
  xlim(c(-118.8, -118)) + ylim(c(33.7, 34.35)) +
  geom_sf(data = la_homicides, aes(color = homicide_race,
                                   fill = homicide_race,
                                   shape = Status)) +
  scale_fill_discrete(name = "Race") +
  scale_color_discrete(name = "Race") +
  scale_shape_manual(values = c(18, 8)) +
  ggtitle("Location of homicides in Los Angeles, CA")
```

